In [11]:
import pandas as pd

In [12]:
df=pd.read_csv("heart_disease_dataset.csv",sep=";")

In [13]:
df

age  sex  chest_pain_type  resting_blood_pressure  cholesterol  \
0     63    1                3                     145          233   
1     37    1                2                     130          250   
2     41    0                1                     130          204   
3     56    1                1                     120          236   
4     57    0                0                     120          354   
..   ...  ...              ...                     ...          ...   
298   57    0                0                     140          241   
299   45    1                3                     110          264   
300   68    1                0                     144          193   
301   57    1                0                     130          131   
302   57    0                1                     130          236   

     fasting_blood_sugar  rest_ecg  max_heart_rate_achieved  \
0                      1         0                      150   
1                      0         1                      187   
2                      0         0                      172   
3                      0         1                      178   
4                      0         1                      163   
..                   ...       ...                      ...   
298                    0         1                      123   
299                    0         1                      132   
300                    1         1                      141   
301                    0         1                      115   
302                    0         0                      174   

     exercise_induced_angina  st_depression  st_slope  num_major_vessels  \
0                          0            2.3         0                  0   
1                          0            3.5         0                  0   
2                          0            1.4         2                  0   
3                          0            0.8         2                  0   
4                          1            0.6         2                  0   
..                       ...            ...       ...                ...   
298                        1            0.2         1                  0   
299                        0            1.2         1                  0   
300                        0            3.4         1                  2   
301                        1            1.2         1                  1   
302                        0            0.0         1                  1   

     thalassemia  target  
0              1       1  
1              2       1  
2              2       1  
3              2       1  
4              2       1  
..           ...     ...  
298            3       0  
299            3       0  
300            3       0  
301            3       0  
302            2       0  

[303 rows x 14 columns]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   age                      303 non-null    int64  
 1   sex                      303 non-null    int64  
 2   chest_pain_type          303 non-null    int64  
 3   resting_blood_pressure   303 non-null    int64  
 4   cholesterol              303 non-null    int64  
 5   fasting_blood_sugar      303 non-null    int64  
 6   rest_ecg                 303 non-null    int64  
 7   max_heart_rate_achieved  303 non-null    int64  
 8   exercise_induced_angina  303 non-null    int64  
 9   st_depression            303 non-null    float64
 10  st_slope                 303 non-null    int64  
 11  num_major_vessels        303 non-null    int64  
 12  thalassemia              303 non-null    int64  
 13  target                   303 non-null    int64  
dtypes: float64(1), int64(13)
m

In [15]:
df.isnull().sum()

age                        0
sex                        0
chest_pain_type            0
resting_blood_pressure     0
cholesterol                0
fasting_blood_sugar        0
rest_ecg                   0
max_heart_rate_achieved    0
exercise_induced_angina    0
st_depression              0
st_slope                   0
num_major_vessels          0
thalassemia                0
target                     0
dtype: int64

In [16]:
import numpy as np

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

def mse_loss(y_true, y_pred):
  # y_true and y_pred are numpy arrays of the same length.
  return ((y_true - y_pred) ** 2).mean()

def mse_loss_derivative(y_true, y_pred):
  # y_true and y_pred are numpy arrays of the same length.
  return (2*(y_true - y_pred))

class ArtificialNeuralNetwork:
    def __init__(self, x, y):
        self.IN   = x
        self.W1   = np.random.rand(self.IN.shape[1],6) 
        self.W2   = np.random.rand(6,4)
        self.W3   = np.random.rand(4,1) 
        self.y    = y
        self.learning_rate = 0.3
    def feed_forward(self):
        self.HIDDEN_LAYER_1 = sigmoid(np.dot(self.IN, self.W1))
        self.HIDDEN_LAYER_2 = sigmoid(np.dot(self.HIDDEN_LAYER_1, self.W2))
        self.output = sigmoid(np.dot(self.HIDDEN_LAYER_2, self.W3))
    def back_propagate(self):
        # application of the chain rule to find derivative of the loss function with respect to W2 and W1
        print(self.HIDDEN_LAYER_1.T)
        d_W3 = np.dot(self.HIDDEN_LAYER_2.T, (mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output)))
        print(d_W3)
        d_W2 = np.dot(self.HIDDEN_LAYER_1.T,  (np.dot(mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output),self.W3.T) * sigmoid_derivative(self.HIDDEN_LAYER_2)))
        d_W1 = np.dot(self.IN.T,  (np.dot(np.dot(mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output), self.W3.T) * sigmoid_derivative(self.HIDDEN_LAYER_2),self.W2.T) * sigmoid_derivative(self.HIDDEN_LAYER_1)))
        # update the weights with the derivative (slope) of the loss function
        self.W1 += self.learning_rate*d_W1
        self.W2 += self.learning_rate*d_W2
        self.W3 += self.learning_rate*d_W3
    
    def train(self, epochs,learning_rate):
        self.learning_rate=learning_rate
        for i in range(epochs):
            self.feed_forward()
            self.back_propagate()
        print("Successfully Trained the Model")
        print("Weights 1:", self.W1)
        print("Weights 2:", self.W2)
        print("Weights 3:", self.W3)
    def predict(self,x):
        HIDDEN_LAYER_1 = sigmoid(np.dot(x, self.W1))
        HIDDEN_LAYER_2 = sigmoid(np.dot(HIDDEN_LAYER_1, self.W2))
        output = sigmoid(np.dot(HIDDEN_LAYER_2, self.W3))
        return output
    
    def print_output(self):
        print(self.output)


    

In [17]:
X = df.drop('target',axis=1).values
y = df['target'].values.reshape(-1,1)

In [18]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X)

In [19]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=42, test_size = 0.2)

In [20]:
ann = ArtificialNeuralNetwork(X,y)
ann.train(500,0.1)

[[0.43182674 0.6381812  0.08411084 ... 0.95136701 0.76130952 0.12189201]
 [0.79511301 0.51379906 0.03817521 ... 0.9900114  0.27490653 0.17972982]
 [0.09003703 0.18287965 0.0714667  ... 0.98836406 0.39948599 0.0998974 ]
 [0.58813491 0.34480265 0.10097512 ... 0.98930318 0.52205355 0.05384078]
 [0.77612494 0.77151558 0.15257067 ... 0.9457982  0.21707041 0.08867976]
 [0.45350331 0.9205503  0.02322895 ... 0.98583058 0.77553637 0.03711987]]
[[-16.98681391]
 [-17.70164034]
 [-14.87954858]
 [-17.90104232]]
[[0.44435481 0.65482919 0.09796452 ... 0.94387042 0.70751094 0.13456479]
 [0.79222582 0.53711195 0.04471391 ... 0.98821585 0.23450478 0.19212589]
 [0.09152166 0.19032682 0.07741462 ... 0.98736706 0.37027253 0.10419102]
 [0.59176586 0.35858779 0.11260864 ... 0.98790013 0.47343057 0.05798497]
 [0.77616979 0.78188632 0.16958146 ... 0.93741407 0.19172857 0.09501977]
 [0.45584312 0.92348888 0.02580488 ... 0.9842516  0.74251631 0.03976934]]
[[8.26690971]
 [8.26515388]
 [7.02466503]
 [8.48616757]]


  9.99007132e-01 6.70678745e-03]]
[[ 0.08103939]
 [ 0.05108314]
 [ 0.13399338]
 [-0.16119289]]
[[6.10105986e-06 2.70803196e-01 9.31774480e-03 ... 9.98903736e-01
  9.99979737e-01 2.36223856e-02]
 [8.63021412e-01 7.27244976e-01 7.63341207e-01 ... 9.99144349e-01
  2.52952840e-01 3.09117764e-01]
 [1.91221921e-03 2.26880759e-02 1.37676452e-04 ... 9.99763222e-01
  5.70336509e-01 4.27771673e-04]
 [8.57331177e-01 9.89111500e-01 3.03013113e-02 ... 9.99999837e-01
  9.82120281e-01 1.54176091e-02]
 [8.11397270e-01 9.83557297e-01 1.17937406e-02 ... 2.13952653e-01
  1.04440212e-01 5.38302310e-02]
 [9.99698129e-01 9.89605715e-01 3.74604765e-04 ... 9.99998760e-01
  9.98902008e-01 6.89641373e-03]]
[[ 0.06784763]
 [ 0.04487667]
 [ 0.11529149]
 [-0.20566163]]
[[6.03691850e-06 2.75296332e-01 9.25458143e-03 ... 9.98934820e-01
  9.99980026e-01 2.34753269e-02]
 [8.62637782e-01 7.26203759e-01 7.71253411e-01 ... 9.99103088e-01
  2.48448393e-01 3.17377946e-01]
 [1.96425259e-03 2.23358625e-02 1.37910606e-04 ... 

[[ 0.02120537]
 [ 0.01066645]
 [ 0.03859066]
 [-0.04191335]]
[[1.29464517e-06 1.20314306e-01 1.21628680e-03 ... 9.99979103e-01
  9.99998923e-01 9.09698223e-03]
 [9.56851336e-01 8.26950216e-01 9.38822676e-01 ... 9.98226928e-01
  8.84053127e-02 7.78746422e-01]
 [5.06498819e-04 1.17771955e-02 2.32849122e-05 ... 9.99865546e-01
  5.65229806e-01 1.57052082e-04]
 [8.56595481e-01 9.95172169e-01 1.20435957e-02 ... 9.99999994e-01
  9.98511475e-01 1.19180519e-02]
 [7.85141144e-01 9.93926372e-01 4.35828300e-03 ... 4.06261274e-02
  5.52289894e-02 1.94935992e-02]
 [9.99953414e-01 9.98683499e-01 6.33384547e-03 ... 9.99933213e-01
  9.14338787e-01 6.51656207e-03]]
[[ 0.02110642]
 [ 0.01062131]
 [ 0.03839205]
 [-0.0416583 ]]
[[1.28857314e-06 1.20126139e-01 1.21398377e-03 ... 9.99979179e-01
  9.99998927e-01 9.08130397e-03]
 [9.56864808e-01 8.27070806e-01 9.38927480e-01 ... 9.98227465e-01
  8.83647796e-02 7.78844835e-01]
 [5.05529607e-04 1.17706620e-02 2.32051393e-05 ... 9.99865706e-01
  5.65404910e-01 1.

In [21]:
threshold = 0.5

In [22]:
print(X_test, y_test)

[[ 0.29046364  0.68100522 -0.93851463  1.04952029  0.57466203 -0.41763453
  -1.00583187 -1.6463164   1.43548113 -0.37924438 -0.64911323  0.26508221
  -2.14887271]
 [ 1.39335191  0.68100522 -0.93851463 -0.3783023   0.14950142  2.394438
   0.89896224  0.58393935 -0.69663055 -0.7243226  -0.64911323  1.24459328
   1.12302895]
 [-0.92271345  0.68100522 -0.93851463  0.47839125  1.25105391 -0.41763453
   0.89896224 -1.29647236  1.43548113  0.65599028 -0.64911323  1.24459328
   1.12302895]
 [ 0.62133012  0.68100522  1.00257707  0.47839125 -1.18395686 -0.41763453
  -1.00583187  0.23409531 -0.69663055  1.69122495 -0.64911323 -0.71442887
  -0.51292188]
 [-0.48155814  0.68100522  1.00257707  0.47839125 -0.25633371 -0.41763453
   0.89896224  0.58393935 -0.69663055 -0.37924438 -0.64911323  0.26508221
   1.12302895]
 [ 1.72421839  0.68100522  1.00257707  1.62064933  0.43938366 -0.41763453
   0.89896224 -1.6463164   1.43548113  1.60495539 -0.64911323  0.26508221
   1.12302895]
 [ 0.18017482  0.6810052

In [23]:
int(ann.predict(X[200])>threshold), y[200]


(0, array([0], dtype=int64))

In [24]:
int(ann.predict(X[0])>threshold), y[0]

(1, array([1], dtype=int64))