In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("heart_disease_dataset.csv",sep=";")

In [3]:
df

age  sex  chest_pain_type  resting_blood_pressure  cholesterol  \
0     63    1                3                     145          233   
1     37    1                2                     130          250   
2     41    0                1                     130          204   
3     56    1                1                     120          236   
4     57    0                0                     120          354   
..   ...  ...              ...                     ...          ...   
298   57    0                0                     140          241   
299   45    1                3                     110          264   
300   68    1                0                     144          193   
301   57    1                0                     130          131   
302   57    0                1                     130          236   

     fasting_blood_sugar  rest_ecg  max_heart_rate_achieved  \
0                      1         0                      150   
1                      0         1                      187   
2                      0         0                      172   
3                      0         1                      178   
4                      0         1                      163   
..                   ...       ...                      ...   
298                    0         1                      123   
299                    0         1                      132   
300                    1         1                      141   
301                    0         1                      115   
302                    0         0                      174   

     exercise_induced_angina  st_depression  st_slope  num_major_vessels  \
0                          0            2.3         0                  0   
1                          0            3.5         0                  0   
2                          0            1.4         2                  0   
3                          0            0.8         2                  0   
4                          1            0.6         2                  0   
..                       ...            ...       ...                ...   
298                        1            0.2         1                  0   
299                        0            1.2         1                  0   
300                        0            3.4         1                  2   
301                        1            1.2         1                  1   
302                        0            0.0         1                  1   

     thalassemia  target  
0              1       1  
1              2       1  
2              2       1  
3              2       1  
4              2       1  
..           ...     ...  
298            3       0  
299            3       0  
300            3       0  
301            3       0  
302            2       0  

[303 rows x 14 columns]

In [75]:
import numpy as np

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

def mse_loss(y_true, y_pred):
  # y_true and y_pred are numpy arrays of the same length.
  return ((y_true - y_pred) ** 2).mean()

def mse_loss_derivative(y_true, y_pred):
  # y_true and y_pred are numpy arrays of the same length.
  return (2*(y_true - y_pred))

class ArtificialNeuralNetwork:
    def __init__(self, x, y):
        self.IN   = x
        self.W1   = np.random.rand(self.IN.shape[1],6) 
        self.W2   = np.random.rand(6,4)
        self.W3   = np.random.rand(4,1) 
        self.y    = y
        self.learning_rate = 0.3
    def feed_forward(self):
        self.HIDDEN_LAYER_1 = sigmoid(np.dot(self.IN, self.W1))
        self.HIDDEN_LAYER_2 = sigmoid(np.dot(self.HIDDEN_LAYER_1, self.W2))
        self.output = sigmoid(np.dot(self.HIDDEN_LAYER_2, self.W3))
    def back_propagate(self):
        # application of the chain rule to find derivative of the loss function with respect to W2 and W1
        print(self.HIDDEN_LAYER_1.T)
        d_W3 = np.dot(self.HIDDEN_LAYER_2.T, (mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output)))
        print(d_W3)
        d_W2 = np.dot(self.HIDDEN_LAYER_1.T,  (np.dot(mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output),self.W3.T) * sigmoid_derivative(self.HIDDEN_LAYER_2)))
        d_W1 = np.dot(self.IN.T,  (np.dot(np.dot(mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output), self.W3.T) * sigmoid_derivative(self.HIDDEN_LAYER_2),self.W2.T) * sigmoid_derivative(self.HIDDEN_LAYER_1)))
        # update the weights with the derivative (slope) of the loss function
        self.W1 += self.learning_rate*d_W1
        self.W2 += self.learning_rate*d_W2
        self.W3 += self.learning_rate*d_W3
    
    def train(self, epochs,learning_rate):
        self.learning_rate=learning_rate
        for i in range(epochs):
            self.feed_forward()
            self.back_propagate()
        print("Successfully Trained the Model")
        print("Weights 1:", self.W1)
        print("Weights 2:", self.W2)
        print("Weights 3:", self.W3)
    def predict(self,x):
        HIDDEN_LAYER_1 = sigmoid(np.dot(x, self.W1))
        HIDDEN_LAYER_2 = sigmoid(np.dot(HIDDEN_LAYER_1, self.W2))
        output = sigmoid(np.dot(HIDDEN_LAYER_2, self.W3))
        return output
    
    def print_output(self):
        print(self.output)


    

In [76]:
X = df.drop('target',axis=1).values
y = df['target'].values.reshape(-1,1)

In [77]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X)

In [78]:
ann = ArtificialNeuralNetwork(X,y)
ann.train(500,0.1)


[[0.95710108 0.9194008  0.04670039 ... 0.98772521 0.19734111 0.06452792]
 [0.63704082 0.08574789 0.12968162 ... 0.9467979  0.33071048 0.22985061]
 [0.73779931 0.24460781 0.20371902 ... 0.98976457 0.27333983 0.13882728]
 [0.98966408 0.76632313 0.06510623 ... 0.99343495 0.0506064  0.15109951]
 [0.577827   0.07823758 0.01092751 ... 0.93388703 0.55186361 0.0511272 ]
 [0.44022682 0.15847936 0.04366333 ... 0.84020766 0.32464081 0.20058003]]
[[-19.0974954 ]
 [-18.60270173]
 [-19.01783089]
 [-18.48236374]]
[[0.95883883 0.92429549 0.05495912 ... 0.98481325 0.1625064  0.0707499 ]
 [0.6438377  0.09257086 0.1544556  ... 0.93327162 0.28310178 0.24924104]
 [0.74454662 0.26310367 0.26312261 ... 0.98460534 0.1992885  0.16232417]
 [0.9897762  0.76962489 0.0679152  ... 0.99306891 0.04792711 0.154408  ]
 [0.58507063 0.08160613 0.01252242 ... 0.92233647 0.49667757 0.05540237]
 [0.44948091 0.16419768 0.05045823 ... 0.81286643 0.28281741 0.21567438]]
[[3.09584341]
 [2.9916162 ]
 [3.01664722]
 [2.75360599]]


 [-0.32806771]]
[[9.99900174e-01 9.80153111e-01 8.80963073e-04 ... 9.99998231e-01
  9.66785498e-01 1.04138299e-03]
 [9.96743129e-01 9.64585045e-01 8.44240719e-01 ... 9.99997400e-01
  9.72585387e-01 4.12909064e-02]
 [9.64733618e-02 7.47005331e-01 8.69879176e-01 ... 9.49160281e-01
  1.20163934e-01 3.38044349e-01]
 [9.55171686e-01 9.14705534e-01 5.79425235e-02 ... 9.99999737e-01
  9.89809433e-01 1.70944842e-02]
 [3.33850091e-02 1.56508737e-01 4.48926407e-02 ... 9.99996538e-01
  9.86261207e-01 1.19922930e-01]
 [6.63929675e-05 4.82329919e-01 2.35787685e-03 ... 9.99993088e-01
  9.99997851e-01 1.06455604e-03]]
[[0.79658894]
 [0.65491522]
 [0.37300547]
 [0.52195724]]
[[9.99892401e-01 9.81252371e-01 9.01370786e-04 ... 9.99998291e-01
  9.68468307e-01 1.00993369e-03]
 [9.97697356e-01 9.64722597e-01 8.34466746e-01 ... 9.99997646e-01
  9.69014370e-01 4.27777740e-02]
 [1.42478361e-01 7.76235722e-01 8.61237247e-01 ... 9.52090442e-01
  1.05421836e-01 3.44551302e-01]
 [9.45955694e-01 9.17149536e-01 6.0

  9.99999681e-01 3.24258923e-04]]
[[-0.05376106]
 [ 0.05312811]
 [-0.00717462]
 [ 0.03935058]]
[[9.99986956e-01 9.99270057e-01 8.48989228e-03 ... 9.99997203e-01
  9.16498931e-01 6.50786398e-04]
 [9.99708458e-01 9.95964431e-01 9.01720306e-01 ... 9.99999898e-01
  9.74837820e-01 1.70881935e-02]
 [1.15126254e-02 8.68764987e-01 9.97702303e-01 ... 3.89551053e-01
  1.25379602e-01 4.39754737e-01]
 [9.08991783e-01 9.93207881e-01 3.21670187e-01 ... 9.99999974e-01
  9.75236235e-01 2.84601699e-02]
 [6.78020410e-03 1.67102626e-01 3.40951760e-02 ... 9.99999761e-01
  9.88844671e-01 1.29662673e-01]
 [1.58267406e-05 5.24097765e-01 4.06935759e-03 ... 9.99943895e-01
  9.99999681e-01 3.22097109e-04]]
[[-0.05323964]
 [ 0.05246698]
 [-0.00718538]
 [ 0.03882353]]
[[9.99986915e-01 9.99271702e-01 8.54325686e-03 ... 9.99997202e-01
  9.16727910e-01 6.47192791e-04]
 [9.99707382e-01 9.95966448e-01 9.01687520e-01 ... 9.99999898e-01
  9.74832449e-01 1.70645701e-02]
 [1.14547779e-02 8.68860414e-01 9.97705820e-01 ... 

  9.99999586e-01 2.10919065e-04]]
[[-0.03083304]
 [ 0.04170442]
 [-0.00227327]
 [ 0.03200151]]
[[9.99936283e-01 9.99676068e-01 7.30082112e-02 ... 9.99959728e-01
  8.21531948e-01 3.56315556e-04]
 [9.99520199e-01 9.91606892e-01 8.65637908e-01 ... 9.99999932e-01
  9.74864812e-01 1.42062966e-02]
 [6.25727281e-03 9.12002779e-01 9.98691595e-01 ... 3.43861777e-01
  8.16551686e-02 5.07470926e-01]
 [7.48028088e-01 9.91294351e-01 4.53543749e-01 ... 9.99999983e-01
  9.78330385e-01 3.28835046e-02]
 [4.55616863e-03 1.61156997e-01 6.86617274e-02 ... 9.99999845e-01
  9.85770822e-01 2.86018609e-01]
 [1.19834715e-05 6.27974700e-01 4.76868253e-03 ... 9.99941023e-01
  9.99999586e-01 2.10383123e-04]]
[[-0.03058048]
 [ 0.04133669]
 [-0.00227239]
 [ 0.03171126]]
[[9.99936028e-01 9.99675316e-01 7.36543437e-02 ... 9.99959500e-01
  8.21002973e-01 3.55259811e-04]
 [9.99520888e-01 9.91564973e-01 8.65721495e-01 ... 9.99999932e-01
  9.74746172e-01 1.42374857e-02]
 [6.23032177e-03 9.12601714e-01 9.98700393e-01 ... 

In [79]:
threshold = 0.5

In [80]:
int(ann.predict(X[200])>threshold), y[200]


(0, array([0], dtype=int64))

In [81]:
int(ann.predict(X[0])>threshold), y[0]

(1, array([1], dtype=int64))